#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.elf.MSP430{1,0,4.3,3
#
eink.xe430: package/cfg/eink.xe430.mak

clean::
	-$(RM) package/cfg/eink.xe430.mak
